ERROR - 2024-09-07 17:19:09 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:306
Stack trace:
#0 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `us...', 0)
#1 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\BaseModel.php(805): CodeIgniter\Model->doInsert(Array)
#6 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Model.php(749): CodeIgniter\BaseModel->insert(Array, false)
#7 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\BaseModel.php(716): CodeIgniter\Model->insert(Array, false)
#8 C:\xampp\htdocs\sarpras\app\Controllers\AuthController.php(56): CodeIgniter\BaseModel->save(Array)
#9 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\CodeIgniter.php(943): App\Controllers\AuthController->attemptRegister()
#10 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\sarpras\public\index.php(79): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\sarpras\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#14 {main}
CRITICAL - 2024-09-07 17:19:09 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\BaseConnection.php on line 647.
 1 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(56): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\AuthController->attemptRegister()
 8 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sarpras\\public\\index.php')
CRITICAL - 2024-09-07 17:19:09 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 311.
 1 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'admin\', \'admin@admin.com\', \'$2y$10$AB4PSG8gYGIXtBn8hGXS5.cAHETonqgOLR0AzkTU.IZoG7IPLqKUK\', \'user\', \'2024-09-07 17:19:09\', \'2024-09-07 17:19:09\')')
 2 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'admin\', \'admin@admin.com\', \'$2y$10$AB4PSG8gYGIXtBn8hGXS5.cAHETonqgOLR0AzkTU.IZoG7IPLqKUK\', \'user\', \'2024-09-07 17:19:09\', \'2024-09-07 17:19:09\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(56): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\AuthController->attemptRegister()
10 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sarpras\\public\\index.php')
CRITICAL - 2024-09-07 17:19:09 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 306.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(306): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'admin\', \'admin@admin.com\', \'$2y$10$AB4PSG8gYGIXtBn8hGXS5.cAHETonqgOLR0AzkTU.IZoG7IPLqKUK\', \'user\', \'2024-09-07 17:19:09\', \'2024-09-07 17:19:09\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'admin\', \'admin@admin.com\', \'$2y$10$AB4PSG8gYGIXtBn8hGXS5.cAHETonqgOLR0AzkTU.IZoG7IPLqKUK\', \'user\', \'2024-09-07 17:19:09\', \'2024-09-07 17:19:09\')')
 3 SYSTEMPATH\Database\BaseConnection.php(607): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (\'admin\', \'admin@admin.com\', \'$2y$10$AB4PSG8gYGIXtBn8hGXS5.cAHETonqgOLR0AzkTU.IZoG7IPLqKUK\', \'user\', \'2024-09-07 17:19:09\', \'2024-09-07 17:19:09\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2307): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `role`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :role:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(327): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(805): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(749): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(716): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(56): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(943): App\Controllers\AuthController->attemptRegister()
11 SYSTEMPATH\CodeIgniter.php(503): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(361): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(79): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sarpras\\public\\index.php')
